# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Model": "01_model.ipynb",
         "TransformerModel": "01_model.ipynb",
         "GRUModel": "01_model.ipynb",
         "get_mean_probs": "02_experiments.ipynb",
         "get_mean_cross_entropy": "02_experiments.ipynb"}

modules = ["model.py",
           "experiments.py"]

doc_url = "https://danaderp.github.io/icodegen/"

git_url = "https://github.com/danaderp/InterpretingCodeGeneration/tree/master/"

def custom_doc_links(name): return None
