# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"remove_non_ascii": "00_data.core.ipynb",
         "beautify_code": "00_data.core.ipynb",
         "extra_tokens": "00_data.core.ipynb",
         "java_reserved_tokens": "00_data.core.ipynb",
         "java_operator_tokens": "00_data.core.ipynb",
         "java_structural_tokens": "00_data.core.ipynb",
         "java_extra_tokens": "00_data.core.ipynb",
         "java_special_tokens": "00_data.core.ipynb",
         "replace_special_tokens": "00_data.core.ipynb",
         "train_tokenizer": "00_data.core.ipynb",
         "java_comment_remover": "01_data.transforms.ipynb",
         "line_randomizer": "01_data.transforms.ipynb",
         "code_token_randomizer": "01_data.transforms.ipynb",
         "transform_df": "01_data.transforms.ipynb",
         "Model": "02_model.core.ipynb",
         "TransformerModel": "02_model.core.ipynb",
         "GRUModel": "02_model.core.ipynb",
         "process_data": "03_cli.ipynb",
         "train": "03_cli.ipynb",
         "evaluate": "03_cli.ipynb",
         "reproduce": "03_cli.ipynb"}

modules = ["data/core.py",
           "data/transforms.py",
           "model/core.py",
           "cli.py"]

doc_url = "https://ArtificialSoftwareEngineering.github.io/icodegen/"

git_url = "https://github.com/ArtificialSoftwareEngineering/icodegen/tree/main/"

def custom_doc_links(name): return None
