# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"beautify_code": "00_data.ipynb",
         "java_reserved_tokens": "00_data.ipynb",
         "java_operator_tokens": "00_data.ipynb",
         "java_structural_tokens": "00_data.ipynb",
         "java_extra_tokens": "00_data.ipynb",
         "extra_tokens": "00_data.ipynb",
         "java_special_tokens": "00_data.ipynb",
         "replace_special_tokens": "00_data.ipynb",
         "train_tokenizer": "00_data.ipynb",
         "Model": "01_model.ipynb",
         "TransformerModel": "01_model.ipynb",
         "GRUModel": "01_model.ipynb",
         "get_mean_probs": "02_experiments.ipynb",
         "get_mean_cross_entropy": "02_experiments.ipynb"}

modules = ["data.py",
           "model.py",
           "experiments.py"]

doc_url = "https://danaderp.github.io/icodegen/"

git_url = "https://github.com/danaderp/InterpretingCodeGeneration/tree/master/"

def custom_doc_links(name): return None
