# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_model.core.ipynb (unless otherwise specified).

__all__ = ['Model', 'TransformerModel', 'GRUModel']

# Cell
import tensorflow as tf

from abc import ABC, abstractmethod

# Cell
class Model(ABC):
    # TODO: Add generating the model config (but only the pieces we care about, i.e., the num layers, heads, dim size, emb size, etc) so that we can easily save it to a file for organizing evaluation results
    def __init__(self, tokenizer, model):
        self.tokenizer = tokenizer
        self.model = model

    @abstractmethod
    def tokenize(self, method):
        pass

    @abstractmethod
    def get_probs(self, inputs):
        pass

    # TODO: Add save method that handles saving model and tokenizer to disc

# Cell

# Tensorflow Huggingface Transformer
class TransformerModel(Model):
    def tokenize(self, method):
        return self.tokenizer(method, return_tensors="tf")

    def get_probs(self, inputs):
        outputs = self.model(inputs)
        logits = outputs[0]
        probs = tf.nn.softmax(logits)

        return probs


# Tensorflow GRU Model
class GRUModel(Model):
    def get_probs(self, method):
        pass